root = "."
tmp_dir = "tmp/auth-service"

[build]
  cmd = "go build -o ./tmp/auth-service/main ./auth-service/cmd"
  bin = "tmp/auth-service/main"
  full_bin = "./tmp/auth-service/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", "testdata", "bin", "api-gateway", "wallet-service", "node_modules"]
  exclude_regex = ["_test.go"]
  delay = 1000